apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:bkX01bDzyUQ3vkbLdA0H7PVW7gmvvNEXkJGY8Jm5onbYnlevcdUN843DWM3I+WfFgJLaxqxTBNpztVE8rmRrkkdeinqy6B0s2gxQ+dFBkKqDXu+4Iffga0BCEM03WHWq/XJ8cy88gO8EPMs9,iv:XtOKTg33BHrZjKj2bwHfiW57jlLDA0YuyPxuJ6C/pNQ=,tag:KpYYMg7Ems0PqxicXuloWw==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2JpMnJJVUpYWjNwSmZW
            SGtSYmZBai9Bc3lsM09CdkxDS0IwV3RmcERjCkY3ekIyTnFERFlFT0JIZ2tGU1Jp
            b1BoYndhT0djS3JQOHQ2OVVlUW1uZ2MKLS0tIDhrUjZZOHlYZzJSeUhGb09LNzhz
            bFljRy9RcGhvUUFnSmlrUkJad1NkS28KGfUXxShnlDvAprvVeccgeGaTKjonsouZ
            MrqES0NVi7wHmTYqZ0GDhM29gcsHH3UTkxUSuULu8zzRAHl4SZAMbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T17:45:56Z"
    mac: ENC[AES256_GCM,data:AJ1vHQnCy/ZCstuffGvN+YPib8p+GtIYfk9ulqQqqjd9f1II7P4QBY+LKcM9HFEqEn+JK0CD0TWaeCZl/LGRvRR6niy5gwihb+Fjo2PzyJ8gusoLVw/FWasVo7wqLBXqabh3kikTn/d3Wtl17BSR/4U43cglEXcIVuiJPXztHdU=,iv:f0OjYEa05ugqqB4Bi232tgtWsTmSMbjsIU1e0WeSzCM=,tag:M/0J9HPWkVf04jBWthv6Fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
