apiVersion: v1
kind: Secret
metadata:
    name: kopia-encryption
    namespace: velero
type: Opaque
stringData:
    repository-password: ENC[AES256_GCM,data:jM7qfd1JsCp9tsW4UTKgvqdsY3ucXZUuySQ1RECXRRnnI1Q1AhIFyCbH1D4=,iv:Gtchy0gQqgw65ttSW73d81LWGg2dwkknzCt3zy+Kvi4=,tag:MdVrAzw3A5xQLfZs+zRFcw==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R1k4bDRkeGJISGpJWnJL
            RFlQUjF0UDJKcUcyMENKTktlTmUrUVJXNkhrCnphdzVkY1d3L2NReTFXeXZQM0di
            Tk0rSzlCLzRqRGd3WVBhWVFrQlNNYmMKLS0tIDdTckJ3UzBySGdXZ3lEWlJFaDRm
            RFRPRmo3dHVkTmRpcEszakZMTWZ3L2cKmAvx7mc4SLqnQ0reYjp9/wcvZdK3144s
            KAS6G8Ip1hkv+k1LczOR5gbZL6BTaIkLa60zqzAjE0yhLFJq//2kqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T17:51:21Z"
    mac: ENC[AES256_GCM,data:sutJspqiVf5Az+rJZuTI3p8e7P01A6jZtD1ugaygFBg9QnKRC4Zd7srm0mIbojF0lofnZcb/5MhbAkwj5EkOKdRbrh+RZambxPWrBy3S1svOvBMRtLUayvB0h+6vcrTw2jPf3v8XTClNAZjrxQtpbdcHelaO8p0Ma4Qt4QSnyrI=,iv:CO1XhIU1koyYiDaT0Z1P27iez23uSx7Zqs1TzoYPJyE=,tag:zkvqTnZ6axQuh/9CzEc7Rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
