apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:K/kjmc6UO0zURmTZCoEVT5v78Jl8KJEguNA8yIZPFBmSVBbdom3VlsnNPXI=,iv:eHPvj++BqPDLxD1CeBR4bZgzu6JGxRVk5IPGLMz5OIk=,tag:5GsLoINg+deakU5NC9vlRA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdFVMd1NwUTgzYlVtSFFr
            bXlxVjhPTlNlVGhwQUp4RmFKdmlsaHVvQkdJCkFDaGNTR2daSjBseE9TWjBuWmdT
            cUc1aFRleVZCaEVrZE96T3BOZC8vdDQKLS0tIDBDU3NjRTgweHpvZks2MHl6V2Rj
            Y2kzNkljdDRhYjRXWjMyZm8rNHZvUTgKoLvaE3+R4/Kwptmet+jOUKdwWnXVIROO
            qKIWcFMBFRxzjprQIn9ENNBC1VLiFQAmD+y4f3Vi08of2MJ7lcbUyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T23:21:02Z"
    mac: ENC[AES256_GCM,data:vdr7ER8EHLPxgr69w+aj8YR1/JpVqrbeuFrkzQcuSMudESzmzlz3FV1CFp6WHf++VnbVoqH2tKDXJV+u9QIYChqrMhfQ4XdvM5OcwUGFZ+YvGylYMDeYV5TtSqEP45PD9we/WZRrbFgL+5aESwpSMfsyYmNd6P7xMXUql7NOUHc=,iv:5ZGinbSOY1koMD5Zxqs6Nh7ggQuDstoFnzp+ZYiYjz0=,tag:S+7c/rzemBPGUNL1wxXKTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
