apiVersion: v1
kind: Secret
metadata:
    name: openclaw-credentials
    namespace: openclaw
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FTUicBfe9w==,iv:b4hbcAo7P+BfZQxZwUcGezWgLnbQYbiDDupcJrL9/HE=,tag:kIB8OVoSbFrpWahwKK8hew==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:meJTl/AuEthmbMkJm64vmWqtKJL5JawUf9y+cCkPEbMSL/KgE2t9t+E36JaWRozi6Q==,iv:N5XQCwGhXvZclNj7SSPVMvauniKZf6YwleSwtAH3ums=,tag:Yaw8f+C1/34a7RFD1qc9Xg==,type:str]
    #ENC[AES256_GCM,data:RM52AWc2DcnByZ+OLfQTMS7+PQClOiaA,iv:39UMALzwa/ykPRKn8QSaSeZPGinWzyvpeoADXNeTG50=,tag:b0gjTwB4Olf5LE9GFW3NBA==,type:comment]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Sbs9liXKTncd5jUQtBBRrHkjtJGFS3Jv4+RB02tnsmY=,iv:HOSDw8xsCgBhomOvLs9o4u/pJnAWoQAXrwAEjC93Hks=,tag:6p3dJ3NXplXd5wSHf1gs4g==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQlF5OXVXR3Z2Z3lBVnox
            cjBVVCszTkJURWJCa3lkbmNsQlUrSEVMWlJvCmJYbHF4SEdWbGVFUk0wSUE2eG56
            WGZrL3hDenFYWVgvUElWc2w1QUVtVnMKLS0tIE1pb1NSUEtzQ1JOUkg5WXpoYUE0
            RGV5QXZuaTZmakVuT3dRbU8wMFNrUW8K9iDq3TrQmVGPzW3PBDx1RjemHQppM6q7
            knU9CteIgputpjDtA/gVEg1KF931LRDIbXoOvwUPst1gbOlVn8PBgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:58:07Z"
    mac: ENC[AES256_GCM,data:J1yWpeXZYXx/HREnCv73FXAQi+Z+Z+G2MLC8rOSezh+VtqWY7qtFMd/g0ogJZPkBwHIcdWlYwITI8hJMa0EkDES41X0zxORAT+14BTxhxPdZ6PfeXD3VPMzo+1bVqClFbh8QHL3D2+/2tj6FxH+te6atOQdepX1gmhAUgeRGR0I=,iv:nH/pr9Qr8F7j3iNo2vri6YA6brhJb6VnQB22S1JSmhk=,tag:pYipSyMlh63jPL1J0R24Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
