apiVersion: v1
kind: Secret
metadata:
    name: openclaw-credentials
    namespace: openclaw
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FTUicBfe9w==,iv:b4hbcAo7P+BfZQxZwUcGezWgLnbQYbiDDupcJrL9/HE=,tag:kIB8OVoSbFrpWahwKK8hew==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:meJTl/AuEthmbMkJm64vmWqtKJL5JawUf9y+cCkPEbMSL/KgE2t9t+E36JaWRozi6Q==,iv:N5XQCwGhXvZclNj7SSPVMvauniKZf6YwleSwtAH3ums=,tag:Yaw8f+C1/34a7RFD1qc9Xg==,type:str]
    #ENC[AES256_GCM,data:RM52AWc2DcnByZ+OLfQTMS7+PQClOiaA,iv:39UMALzwa/ykPRKn8QSaSeZPGinWzyvpeoADXNeTG50=,tag:b0gjTwB4Olf5LE9GFW3NBA==,type:comment]
    OPENCLAW_GATEWAY_TOKEN: ""
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQlF5OXVXR3Z2Z3lBVnox
            cjBVVCszTkJURWJCa3lkbmNsQlUrSEVMWlJvCmJYbHF4SEdWbGVFUk0wSUE2eG56
            WGZrL3hDenFYWVgvUElWc2w1QUVtVnMKLS0tIE1pb1NSUEtzQ1JOUkg5WXpoYUE0
            RGV5QXZuaTZmakVuT3dRbU8wMFNrUW8K9iDq3TrQmVGPzW3PBDx1RjemHQppM6q7
            knU9CteIgputpjDtA/gVEg1KF931LRDIbXoOvwUPst1gbOlVn8PBgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:51:51Z"
    mac: ENC[AES256_GCM,data:YpuBQUDfIjI7NX0umtZcJ4zZVz3uwL5XjFlUq1svrSKDjcG72cJSFr2NLV97lwlGAcgR3/hU0j8RxnXrgW3BP00idGXpWvA4xGVDuP4UAJuWFfsYyfq88WqNxAQmASCdouA21BPEWh0oLCDuDDufAzcCUVbfVy24P9+BMepOlPY=,iv:O21lwA1JOI91OzPDHlTUvLUmXgysA+BrTkOJ8lNX5S0=,tag:SSd403I6ZPQjz8RJrGA+Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
