---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: https://authentik.pxldi.de/outpost.goauthentik.io/auth/traefik/forward
    trustForwardHeader: true
    authResponseHeaders:
      - X-Authentik-User
      - X-Authentik-Email
      - X-Authentik-Groups
      - X-Authentik-Name
