apiVersion: v1
kind: Secret
metadata:
  name: authentik-credentials
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "CHANGE_ME"
  AUTHENTIK_POSTGRES_PASSWORD: "CHANGE_ME"
  AUTHENTIK_POSTGRES_USER: "authentik"
  AUTHENTIK_POSTGRES_DB: "authentik"
