apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:UZYNg5wTO+ozDTdTOTrQIy+16j/c50Emkuan7MP3EdCovMef+1Op9w==,iv:7elQfmUIK0LopJxAR0R55pcdBTTKaJoqRv8Jj1L2450=,tag:znIi5L2Wwl0uCO0zNfNr/A==,type:str]
    CLOUDFLARE_ZONE: ENC[AES256_GCM,data:6HpVsLrCu3Y=,iv:xTPOL/xvDdhUcbVH6sq+F0OBpPA7k5aknkJzcbrfbCc=,tag:R1pmzkFKZi81oD14++ohGQ==,type:str]
    CLOUDFLARE_SUBDOMAIN: ENC[AES256_GCM,data:/A==,iv:EfgVZyNytENEIjVWIomwK2hC0pNQPyfaYPuZpG/oIoI=,tag:sYc2TuIqnjJBD/VMvuaEOg==,type:str]
    CLOUDFLARE_PROXIED: ENC[AES256_GCM,data:8hlVkX4=,iv:e87H5OyUE3fUuucb4kjJeqrDAOP1diWlAaJJAS+NkiY=,tag:Y/A7gaCEP9Q67Fu7jAyeRA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a25VOGZIV09qOEthcGxM
            eDhBaG10K0VOT1k1a2pjb0E1UWN1Vzc5VHdVCm1Vd2Fic2IzZ2tDdlF6RVh0YXhW
            ZzlYMS9sZDdTNktUbWNnUHVJSjNVM1EKLS0tIHZoOE9mMTVyQjRYS3hON0FIWXNi
            TGE5WUVDQXo5VFloN0kzZWtvR1lWMVkKFaetQscvPU6cqvSaa19m8qNztlBfTVzr
            BbwF65EKRrqy6oiT5F0zsCenMaLYnDyxi80AWlgVK9QpprUiNWa9Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T23:25:26Z"
    mac: ENC[AES256_GCM,data:A6NRB+RBnuEpzeUWfyl3MI49QY5Qm3ESPb+JDPivuxvfg3EETSDEi/OYjyqejpE6qFnqB+xcMm1xBkxGm+ds+I86gtfgBLqBDlhq9+Ues2QX/RgNXubmBvrVvc1yE4wRz0sosw4YAdNjwDfyHCEivM2qRjioYYcFosj3TosoVsw=,iv:Q35ZJ2WpgAASZuW2GGMaQwiUNjVmHNl2ad40tLyHxVc=,tag:yGlejmyWU7iciQr25nEJ/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
