apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-ddns
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:UZYNg5wTO+ozDTdTOTrQIy+16j/c50Emkuan7MP3EdCovMef+1Op9w==,iv:7elQfmUIK0LopJxAR0R55pcdBTTKaJoqRv8Jj1L2450=,tag:znIi5L2Wwl0uCO0zNfNr/A==,type:str]
    CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:jggPV6vQEV+XpKYdvHhG3c/meDBth6vr5ow/ZzJdnY4=,iv:rxxSDmryU169/mDUrx23c0fIlfYT7e6506Rr5YadAhA=,tag:QdowHEbD55AmMZnzYH4aVw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+9NJKlv63/9gxw==,iv:7eUsO7lx4IaONdfvnQ1ObEMkiehfaZB9ZuYEMm5i9t0=,tag:MJW3Mf2GCC5aT6jdVpiCxA==,type:str]
sops:
    age:
        - recipient: age14xuuf3xthzqf679mncw0xqwj9thc99yh5e5r34t0cvmkhjx8kakqv0njl0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a25VOGZIV09qOEthcGxM
            eDhBaG10K0VOT1k1a2pjb0E1UWN1Vzc5VHdVCm1Vd2Fic2IzZ2tDdlF6RVh0YXhW
            ZzlYMS9sZDdTNktUbWNnUHVJSjNVM1EKLS0tIHZoOE9mMTVyQjRYS3hON0FIWXNi
            TGE5WUVDQXo5VFloN0kzZWtvR1lWMVkKFaetQscvPU6cqvSaa19m8qNztlBfTVzr
            BbwF65EKRrqy6oiT5F0zsCenMaLYnDyxi80AWlgVK9QpprUiNWa9Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T22:25:58Z"
    mac: ENC[AES256_GCM,data:ZjV/WSTEdM+Aa+llTuN+7HBGsKu0FUPflWci0Y+cSU8n3cvFTVhVOhKJzl9Kc4nvQU5XP8peFXFY+SVaY02d4mHR9tuzWI6SmpyN0s1IAqBPrX3iuoK/YDITLctItefIqU870E8lfOWvFB60h4EJ8E+YsmxGzjuSzyxDNiPMqxQ=,iv:lvdvKEzDYxBMqE4bK5xiQrnelDVmESkZE6m11X1sCyA=,tag:JV47MRhf6sjkU7MbXSW4yw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
